Basler camera integration with ophyd
BNL-ATF/profile_atf pull request #4
Opened 2022-12-05 17:26 UTC by thomaswmorris

2022-12-05 17:27 UTC, thomaswmorris commented
30-basler.py runs with the PylonViewer camera emulation, but we may need to tweak it for an actual camera

2022-12-05 17:43 UTC, mrakitin requested changes
It needs some work. I don't see where the `resource` and `datum` documents are generated.

Also, please use the CI config from #2 and update the tests to make sure it works in the CI environment as expected. Some ideas from https://github.com/NSLS-II/profile-collection-ci/blob/main/.azure-templates/run-tests.yml can be useful.

2022-12-05 17:43 UTC, mrakitin commented on startup/30-basler.py
> +                    root_dir='/tmp/sirepo_det_data', **kwargs):
The args/kwargs need to be revised as they are not relevant to this implementation.

2022-12-05 17:43 UTC, mrakitin commented on startup/30-basler.py
> +        self.camera_object.Close()
I think these lines can be moved to the `stage` method. This way we don't "touch" the camera API on instantiation, but rather access the API on explicit use.

2022-12-05 17:43 UTC, mrakitin commented on startup/30-basler.py
> +    def grab_images(self, num=10):
I suggest making it a private method (i.e. `_grab_images`).

2022-12-05 17:43 UTC, mrakitin commented on startup/30-basler.py
> +        self.camera_object.PixelFormat.SetValue(desired_pixel_format)
This block of code can go to the `stage` method too.

2022-12-05 17:43 UTC, mrakitin commented on startup/30-basler.py
> +        image = self.grab_images(num=10)
I think we should use 1 image per trigger, e.g. for the `bp.count` plan, it will produce one image per count.

2022-12-05 17:43 UTC, mrakitin commented on startup/30-basler.py
> +        self.camera_object.Close()
This `...Close()` call will better happen in the `unstage` method. That method should also revert the parameters to their original values.

2022-12-05 17:43 UTC, mrakitin commented on startup/30-basler.py
> +cam.trigger()
Normally we don't call `trigger` in the startup files. That can interfere with the already running scan and can result in a weird state.

2022-12-16 00:14 UTC, mrakitin commented
Closing it in favor of #6.

2022-12-16 00:14 UTC, closed without merging